services:
  duckdns:
    image: linuxserver/duckdns:latest
    container_name: duckdns
    restart: unless-stopped
    environment:
      - SUBDOMAINS=<sub_dominio> # Subdominio (sin ".duckdns.org"). Para añadir más de 1 subdominio, separar por "," : subdominio1,subdominio2,subdominio3...
      - TOKEN=<token> # Tocken de Duck DNS
      - TZ=Europe/Madrid
      - LOG_FILE=true
    volumes:
      - ./logs:/config
